/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractSol from "./Contract.sol";
export type { contractSol };
export type { Lock } from "./Lock";
